/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "Clock_1.h"
#include "MOSI.h"
#include "MOSI_aliases.h"
#include "SCLK.h"
#include "SCLK_aliases.h"
#include "SS.h"
#include "SS_aliases.h"
#include "MISO.h"
#include "MISO_aliases.h"
#include "PWMn.h"
#include "PWMn_aliases.h"
#include "PWM.h"
#include "PWM_aliases.h"
#include "Clock_2.h"
#include "isr_1.h"
#include "PWM_1.h"
#include "SPI_1.h"
#include "SPI_1_SPI_UART.h"
#include "SPI_1_PINS.h"
#include "SPI_1_SPI_UART_PVT.h"
#include "SPI_1_PVT.h"
#include "SPI_1_BOOT.h"
#include "LED_DOUT.h"
#include "LED_DOUT_aliases.h"
#include "FRAME_SYNC.h"
#include "FRAME_SYNC_aliases.h"
#include "LED_SCLKnc.h"
#include "LED_SCLKnc_aliases.h"
#include "SPI_1_SCBCLK.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

