static char *banner_string[] = {
"    My wife told me to stop impersonating a flamingo. I had to put my foot down.        ",
"    I failed math so many times at school, I can't even count.        ",
"    I was wondering why the frisbee kept getting bigger and bigger, but then it hit me.        ",
"    I heard there were a bunch of break-ins over at the car park. That is wrong on so many levels.        ",
"    I want to die peacefully in my sleep, like my grandfather. Not screaming and yelling like the passengers in his car.        ",
"    When life gives you melons, you might be dyslexic.        ",
"    Don't you hate it when someone answers their own questions? I do.        ",
"    It takes a lot of balls to golf the way I do.        ",
"    I know they say that money talks, but all mine says is 'Goodbye.'        ",
"    My dad has multiple personalities, but he's good people.        ",
"    The problem with kleptomaniacs is that they always take things literally.        ",
"    I can't believe I got fired from the calendar factory. All I did was take a day off.        ",
"    Most people are shocked when they find out how bad I am as an electrician.        ",
"    Never trust atoms; they make up everything.        ",
"    My wife just found out I replaced our bed with a trampoline. She hit the ceiling!        ",
"    I was addicted to the hokey pokey, but then I turned myself around.        ",
"    I used to think I was indecisive. But now I'm not so sure.        ",
"    Russian dolls are so full of themselves.        ",
"    Light travels faster than sound, which is the reason that some people appear bright before you hear them speak.        ",
"    My therapist says I have a preoccupation for revenge. We'll see about that.        ",
"    I'm reading a book about anti-gravity. It's impossible to put down.        ",
"    'Doctor, there's a patient on line one that says he's invisible.' 'Well, tell him I can't see him right now.'        ",
"    Atheism is a non-prophet organization.        ",
"    A recent study has found that women who carry a little extra weight live longer than the men who mention it.        ",
"    The future, the present, and the past walk into a bar. Things got a little tense.        ",
"    Before you criticize someone, walk a mile in their shoes. That way, when you do criticize them, you're a mile away and you have their shoes.        ",
"    Last night my girlfriend was complaining that I never listen to her… or something like that.        ",
"    Maybe if we start telling people their brain is an app, they'll want to use it.        ",
"    If a parsley farmer gets sued, can they garnish his wages?        ",
"    I got a new pair of gloves today, but they're both 'lefts,' which on the one hand is great, but on the other, it's just not right.        ",
"    I didn't think orthopedic shoes would help, but I stand corrected.        ",
"    People who take care of chickens are literally chicken tenders.        ",
"    It was an emotional wedding. Even the cake was in tiers.        ",
"    I just got kicked out of a secret cooking society. I spilled the beans.        ",
"    Blunt pencils are really pointless.        ",
"    Two Wi-Fi engineers got married. The reception was fantastic.        ",
"    Just got fired from my job as a set designer. I left without making a scene.        ",
"    What's the difference between ignorance and apathy? Don't know and don't care.        ",
"    One of the cows didn't produce milk today. It was an udder failure.        ",
"    Adam & Eve were the first ones to ignore the Apple terms and conditions.        ",
"    Refusing to go to the gym is a form of resistance training.        ",
"    If attacked by a mob of clowns, go for the juggler.        ",
"    The man who invented Velcro has died. RIP.        ",
"    Despite the high cost of living, it remains popular.        ",
"    A dung beetle walks into a bar and asks, 'Is this stool taken?'        ",
"    The rotation of Earth really makes my day.        ",
"    Well, to be Frank with you, I'd have to change my name.        ",
"    What if there were no hypothetical questions?        ",
"    The world champion tongue twister got arrested. I hear they're going to give him a tough sentence.        ",
"    Pollen is what happens when flowers can't keep it in their plants.        ",
"    A book fell on my head the other day. I only have my shelf to blame though.        ",
"    Communist jokes aren't funny unless everyone gets them.        ",
"    Geology rocks, but geography's where it's at.        ",
"    My friend's bakery burned down last night. Now his business is toast.        ",
"    Four fonts walk into a bar. The bartender says, 'Hey! We don't want your type in here!'        ",
"    If you don't pay your exorcist, do you get repossessed?        ",
"    When the cannibal showed up late to the buffet, they gave him the cold shoulder.        ",
"    The first time I got a universal remote control, I thought to myself, 'This changes everything.'        ",
"    How do you make holy water? You boil the hell out of it.        ",
"    Whiteboards are remarkable.        ",
"    I threw a boomerang a couple years ago; I now live in constant fear.        ",
"    I put my grandma on speed dial the other day. I call it insta-gram.        ",
"    'I have a split personality,' said Tom, being Frank.        ",
"    Will glass coffins be a success? Remains to be seen.        "};
