static char *banner_string[] = {
    "ROAR  On the other hand, you have different fingers.        ",
    "ROAR  Cross country skiing is great if you live in a small country.        ",
    "ROAR  I spilled spot remover on my dog. Now he's gone.        ",
    "ROAR  If you're not part of the solution, you're part of the precipitate.        ",
    "ROAR  I have two very rare photographs. One is a picture of Houdini locking his keys in his car.        ",
    "ROAR  I stayed up all night playing poker with tarot cards. I got a full house and four people died.        ",
    "ROAR  I used to work in a fire hydrant factory. You couldn't park anywhere near the place.        ",
    "ROAR  It's a small world, but I wouldn't want to have to paint it.        ",
    "ROAR  Right now I'm having amnesia and deja vu at the same time.        ",
    "ROAR  What's another word for Thesaurus?        ",
    "ROAR  When I get real bored, I like to drive downtown and get a great parking spot, then sit in my car and count how many people ask me if I'm leaving.        ",
    "ROAR  You can't have everything. Where would you put it?        ",
    "ROAR  I planted some bird seed. A bird came up. Now I don't know what to feed it.        ",
    "ROAR  My aunt gave me a walkie-talkie for my birthday. She says if I'm good, she'll give me the other one next year.        ",
    "ROAR  I eat swiss cheese from the inside out.        ",
    "ROAR  I had amnesia once or twice.        ",
    "ROAR  The sun never sets on the British Empire. But it rises every morning. The sky must get awfully crowded.        ",
    "ROAR  I was in the grocery store. I saw a sign that said \"pet supplies\". So I did. Then I went outside and saw a sign that said \"compact cars\".        ",
    "ROAR  I wear my heart on my sleeve. I wear my liver on my pant leg.        ",
    "ROAR  If you can wave a fan, and you can wave a club, can you wave a fan club?        ",
    "ROAR  When I was in boy scouts, I slipped on the ice and hurt my ankle. A little old lady had to help me across the street.        ",
    "ROAR  You know how it is when you're reading a book and falling asleep, you're reading, reading...and all of a sudden you notice your eyes are closed? I'm like that all the time.        ",
    "ROAR  My roommate got a pet elephant. Then it got lost. It's in the apartment somewhere.        ",
    "ROAR  Smoking cures weight problems ... eventually ...        ",
    "ROAR  I took a course in speed waiting. Now I can wait an hour in only ten minutes.        ",
    "ROAR  I eat swiss cheese. But I only nibble on it. I make the holes bigger.        ",
    "ROAR  I moved into an all-electric house. I forgot and left the porch light on all day. When I got home the front door wouldn't open.        ",
    "ROAR  I got a garage door opener. It can't close. Just open.        ",
    "ROAR  You know how it is when you go to be the subject of a psychology experiment, and nobody else shows up, and you think maybe that's part of the experiment? I'm like that all the time.        ",
    "ROAR  There aren't enough days in the weekend.        ",
    "ROAR  Is \"tired old cliche\" one?        ",
    "ROAR  The sign said \"eight items or less\". So I changed my name to Les.        ",
    "ROAR  In school, every period ends with a bell. Every sentence ends with a period. Every crime ends with a sentence.        ",
    "ROAR  I went to a garage sale. \"How much for the garage?\" \"It's not for sale.\"        ",
    "ROAR  I know the guy who writes all those bumper stickers. He hates New York.        ",
    "ROAR  I washed a sock. Then I put it in the dryer. When I took it out, it was gone.        ",
    "ROAR  The Bermuda Triangle got tired of warm weather. It moved to Alaska. Now Santa Claus is missing.        ",
    "ROAR  I went to a fancy french restaurant called \"Deja Vu.\" The headwaiter said, \"Don't I know you?\"        ",
    "ROAR  Last week I forgot how to ride a bicycle.        ",
    "ROAR  I took lessons in bicycle riding. But I could only afford half of them. Now I can ride a unicycle.        ",
    "ROAR  I had some eyeglasses. I was walking down the street when suddenly the prescription ran out.        ",
    "ROAR  I got food poisoning today. I don't know when I'll use it.        ",
    "ROAR  When I turned two I was really anxious, because I'd doubled my age in a year. I thought, if this keeps up, by the time I'm six I'll be ninety.        ",
    "ROAR  Sponges grow in the ocean. That just kills me. I wonder how much deeper the ocean would be if that didn't happen.        ",
    "ROAR  I put instant coffee in a microwave oven and almost went back in time.        ",
    "ROAR  Even snakes are afraid of snakes.        ",
    "ROAR  I can't stop thinking like this.        ",
    "ROAR  This isn't all true.        ",
    "ROAR  You know how it is when you're walking up the stairs, and you get to the top, and you think there's one more step? I'm like that all the time.        ",
    "ROAR  I put hardwood floors on top of wall-to-wall carpet.        ",
    "ROAR  Two babies were born on the same day at the same hospital. They lay there and looked at each other. Their families came and took them away. Eighty years later, by a bizarre coincidence, they lay in the same hospital, on their deathbeds, next to each other. One of them looked at the other and said, \"So. What did you think?\"        ",
    "ROAR  What are imitation rhinestones?        ",
    "ROAR  If a word in the dictionary were misspelled, how would we know?        ",
    "ROAR  If God dropped acid, would he see people?        ",
    "ROAR  In my house there's this light switch that doesn't do anything. Every so often I would flick it on and off just to check. Yesterday, I got a call from a woman in Madagascar. She said, \"Cut it out.\"        ",
    "ROAR  It's a good thing we have gravity or else when birds died they'd just stay right up there. Hunters would be all confused.        ",
    "ROAR  I wrote a few children's books...not on purpose.        ",
    "ROAR  I got up one morning, couldn't find my socks, so I called Information. She said, \"Hello, Information.\" I said, \"I can't find my socks.\" She said, \"They're behind the couch.\" And they were!        ",
    "ROAR  When I was a little kid we had a sand box. It was a quicksand box. I was an only child....eventually.        ",
    "ROAR  [Referring to a glass of water:] I mixed this myself. Two parts H, one part O. I don't trust anybody!        ",
    "ROAR  I'm moving to Mars next week, so if you have any boxes...        ",
    "ROAR  I saw a bank that said \"24 Hour Banking\", but I don't have that much time.        ",
    "ROAR  I went to the museum where they had all the heads and arms from the statues that are in all the other museums.        ",
    "ROAR  I went to a restaurant that serves \"breakfast at any time\". So I ordered French Toast during the Renaissance.        ",
    "ROAR  I went to a general store. They wouldn't let me buy anything specifically.        ",
    "ROAR  I went to a 7-11 and asked for a 2x4 and a box of 3x5's. The clerk said, \"ten-four.\"        ",
    "ROAR  I went down the street to the 24-hour grocery. When I got there, the guy was locking the front door. I said, \"Hey, the sign says you're open 24 hours.\" He said, \"Yes, but not in a row.\"        ",
    "ROAR  I love to go shopping. I love to freak out salespeople. They ask me if they can help me, and I say, \"Have you got anything I'd like?\" Then they ask me what size I need, and I say, \"Extra medium.\"        ",
    "ROAR  I saw a small bottle of cologne and asked if it was for sale. She said, \"It's free with purchase.\" I asked her if anyone bought anything today.        ",
    "ROAR  There was a power outage at a department store yesterday. Twenty people were trapped on the escalators.        ",
    "ROAR  I bought my brother some gift-wrap for Christmas. I took it to the Gift Wrap department and told them to wrap it, but in a different print so he would know when to stop unwrapping.        ",
    "ROAR  For my birthday I got a humidifier and a de-humidifier...I put them in the same room and let them fight it out.        ",
    "ROAR  Ever notice how irons have a setting for *permanent* press? I don't get it...        ",
    "ROAR  Today I dialed a wrong number... The other person said, \"Hello?\" and I said, \"Hello, could I speak to Joey?\"... They said, \"Uh... I don't think so... he's only 2 months old.\" I said, \"I'll wait.\"        ",
    "ROAR  I installed a skylight in my apartment... The people who live above me are furious!        ",
    "ROAR  All of the people in my building are insane. The guy above me designs synthetic hairballs for ceramic cats. The lady across the hall tried to rob a department store...with a pricing gun. She said, \"Give me all of the money in the vault, or I'm marking down everything in the store.\"        ",
    "ROAR  Doing a little work around the house. I put fake brick wallpaper over a real brick wall, just so I'd be the only one who knew. People come over and I'm gonna say, \"Go ahead, touch it...it feels real.\"        ",
    "ROAR  In my house on the ceilings I have paintings of the rooms above...so I never have to go upstairs.        ",
    "ROAR  One time the power went out in my house and I had to use the flash on my camera to see my way around. I made a sandwich and took fifty pictures of my face. The neighbors thought there was lightning in my house.        ",
    "ROAR  I have a microwave fireplace in my house... The other night I laid down in front of the fire for the evening in two minutes.        ",
    "ROAR  I bought a house, on a one-way dead-end road. I don't know how I got there.        ",
    "ROAR  My house is made out of balsa wood, so when I want to scare the neighborhood kids I lift it over my head and tell them to get out of my yard or I'll throw it at them.        ",
    "ROAR  My house is on the median strip of a highway. You don't really notice, except I have to leave the driveway doing 60 MPH.        ",
    "ROAR  For a while I didn't have a car... I had a helicopter... no place to park it, so I just tied it to a lamp post and left it running... [slow glance upward]        ",
    "ROAR  I hooked up my accelerator pedal in my car to my brake lights. I hit the gas, people behind me stop, and I'm gone.        ",
    "ROAR  I replaced the headlights in my car with strobe lights, so it looks like I'm the only one moving.        ",
    "ROAR  I play the harmonica. The only way I can play is if I get my car going really fast, and stick it out the window. I put a new engine in my car, but forgot to take the old one out. Now my car goes 500 miles per hour. The harmonica sounds *amazing*.        ",
    "ROAR  I watched the Indy 500, and I was thinking that if they left earlier they wouldn't have to go so fast.        ",
    "ROAR  I had to stop driving my car for a while...the tires got dizzy.        ",
    "ROAR  My neighbor has a circular driveway...he can't get out.        ",
    "ROAR  I have an answering machine in my car. It says, \"I'm home now. But leave a message and I'll call when I'm out.\"        ",
    "ROAR  I saw a sign: \"Rest Area 25 Miles\". That's pretty big. Some people must be really tired.        ",
    "ROAR  I was going 70 miles an hour and got stopped by a cop who said, \"Do you know the speed limit is 55 miles per hour?\" \"Yes, officer, but I wasn't going to be out that long...\"        ",
    "ROAR  One time a cop pulled me over for running a stop sign. He said, \"Didn't you see the stop sign?\" I said, \"Yeah, but I don't believe everything I read.\"        ",
    "ROAR  I got my driver's license photo taken out of focus on purpose. Now when I get pulled over the cop looks at it (moving it nearer and farther, trying to see it clearly)...and says, \"Here, you can go.\"        ",
    "ROAR  The judge asked, \"What do you plead?\" I said, \"Insanity, your honour, who in their right mind would park in the passing lane?\"        ",
    "ROAR  Yesterday I parked my car in a tow-away zone ... when I came back the entire area was missing.        ",
    "ROAR  I hate it when my foot falls asleep during the day because that means it's going to be up all night.        ",
    "ROAR  When I woke up this morning my girlfriend asked me, \"Did you sleep well?\" I said, \"No, I made a few mistakes.\"        ",
    "ROAR  I was trying to daydream, but my mind kept wandering.        ",
    "ROAR  One night I walked home very late and fell asleep in somebody's satellite dish. My dreams were showing up on TV's all over the world.        ",
    "ROAR  There's a fine line between fishing and standing on the shore looking like an idiot.        ",
    "ROAR  The other day, I was walking my dog around my building ... on the ledge. Some people are afraid of heights. Not me, I'm afraid of widths.        ",
    "ROAR  I was born by Caesarian section ... but not so you'd notice. It's just that when I leave a house, I go out through the window.        ",
    "ROAR  When I was little, my grandfather used to make me stand in a closet for five minutes without moving. He said it was elevator practice.        ",
    "ROAR  I didn't get a toy train like the other kids. I got a toy subway instead. You couldn't see anything, but every now and then you'd hear this rumbling noise go by"
};
